apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: olm-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.olm.replicaCount }}
  selector:
    matchLabels:
      app: olm-operator
  template:
    metadata:
      labels:
        app: olm-operator
    spec:
      serviceAccountName: olm-operator-serviceaccount
      volumes:
        - name: srv-cert
          secret:
            secretName: srv-cert
        - name: profile-collector-cert
          secret:
            secretName: profile-collector-cert
      containers:
        - name: olm-operator
          volumeMounts:
          - name: srv-cert
            mountPath: "/srv-cert"
            readOnly: true
          - name: profile-collector-cert
            mountPath: "/profile-collector-cert"
            readOnly: true
          command:
          - /bin/olm
          args:
          - --namespace
          - $(OPERATOR_NAMESPACE)
          {{- if .Values.watchedNamespaces }}
          - --watchedNamespaces
          - {{ .Values.watchedNamespaces }}
          {{- end }}
          {{- if .Values.olm.commandArgs }}
          - {{ .Values.olm.commandArgs }}
          {{- end }}
          {{- if .Values.debug }}
          - --debug
          {{- end }}
          {{- if .Values.writeStatusName }}
          - --writeStatusName
          - {{ .Values.writeStatusName }}
          {{- end }}
          {{- if .Values.writePackageServerStatusName }}
          - --writePackageServerStatusName
          - {{ .Values.writePackageServerStatusName }}
          {{- end }}
          {{- if .Values.olm.tlsCertPath }}
          - --tls-cert
          - {{ .Values.olm.tlsCertPath }}
          {{- end }}
          {{- if .Values.olm.tlsKeyPath }}
          - --tls-key
          - {{ .Values.olm.tlsKeyPath }}
          {{- end }}
          image: {{ .Values.olm.image.ref }}
          imagePullPolicy: {{ .Values.olm.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.olm.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.olm.service.internalPort }}
              scheme: {{ if and .Values.olm.tlsKeyPath .Values.olm.tlsCertPath }}HTTPS{{ else }}HTTP{{end}}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.olm.service.internalPort }}
              scheme: {{ if and .Values.olm.tlsKeyPath .Values.olm.tlsCertPath }}HTTPS{{ else }}HTTP{{end}}
          terminationMessagePolicy: FallbackToLogsOnError
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: olm-operator
          {{- if .Values.olm.resources }}
          resources:
{{ toYaml .Values.olm.resources | indent 12 }}
          {{- end}}
    {{- if .Values.olm.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.olm.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.olm.tolerations }}
      tolerations:
{{ toYaml .Values.olm.tolerations | indent 6 }}
    {{- end }}
