name: Upstream Sync
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  clone:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: |
        echo "https://${{ github.actor }}:${{ github.token }}@github.com" >> "${HOME}/.git-credentials"
        git config --global credential.helper store
        git clone "https://github.com/${{ github.repository }}.git" -b master
        git remote add -f upstream https://github.com/operator-framework/operator-lifecycle-manager.git
        git merge --ff-only upstream/master
